### ISSUE TITLE
Preferencias para paciente.

### ISSUE THREAD

**Issue by BCavagion** [igrowker/i004-mindup-back#37]
Seleccionar psicologo por edad y por genero

**Comment by eduardoe92** [comment]
URL: http://localhost:8090/api/core/search-preference-psychologists
Action: POST.

Endpoint para visualizar las preferencias de los pacientes.

Se visualizarán los psicólogos que sea mayor o menor a 35 años, Masculinos o Femeninos. 

Datos a ingresar para buscar los psicólogos:

{
  "isBelow35": true or false, 
  "gender": "FEMALE" o "MALE"
}

Notas:

- TRUE para menor a 35 años.
- FALSE para mayor a 35 años.
- Basándose en la fecha de nacimiento ingresada por el usuario "PSYCHOLOGIST" se calculará su edad.
- La edad no se guarda en la base de datos. 
- Siempre definir el genero del psicólogo que deseas que te atienda, en este caso "FEMALE" o "MALE".
