### ISSUE TITLE
Corroborar datos de Usuario

### ISSUE THREAD

**Issue by BCavagion** [igrowker/i004-mindup-back#41]
Fecha de nacimiento:
Nombre completo:
Ubicación: 
Genero:
Matricula:
Especialidad: 
Sobre ti:

**Comment by eduardoe92** [comment]
URL: http://localhost:8090/api/core/user/{userId}/profile
Action: PUT.

Endpoint para editar los datos del usuario.

Datos a ingresar:

{
    "information": "Informacion sobre el usuario",
    "name": "Nombre del usuario",
    "birth": "Fecha de nacimiento, formato yyyy-MM-dd",
    "gender": "MALE/FEMALE/OTHER",
    "phone": "Telefono celular",
    "location": "Ciudad"

    Datos adicionales unicamente para el rol de PSYCHOLOGIST
    "tuition": "Matricula (solo números)",
    "specialty": "Especialidad del psicólogo",
}
